### PR TITLE
rename ruby-gemset and version for rvm

### PR DESCRIPTION
**Pull request by sigu**
`ruby-version` and `ruby-gemset` cannot be picked up by rvm so I had to add a `.` to the beginning of the file names for this to work well `.ruby-version` and `.ruby-gemset`

### CODE REVIEW

**Review by diraulo — APPROVED** [review]

**Review by tochman — APPROVED** [review]
Great catch.

**Comment by FedericoEsparza** [comment]
Since the project is in its early stages you might also consider adding the Rails version to the gemset name. This is helpful when switching between gemsets after having upgraded gem versions a few times.
 
Running a command like this creates/updates both the `.ruby-version` and `.ruby-gemset` files with the necessary dots:
  
`rvm use ruby-2.3.1@visualizer-rails5.0 --ruby-version --create`
  
Just a suggestion.

**Comment by sigu** [comment]
@FedericoEsparza specifying the rails version might mean one creates a new gemset if we upgrade to `rails5.1` or having it as `rails5.0` while rails has been upgraded will be misleading.
I prefer naming gemsets after projects 😄

**Comment by tochman** [comment]
You are both making good points @FedericoEsparza & @sigu I would accept the solution the chore owner decides upon. Imo this can be merged @lollypop27

**Comment by FedericoEsparza** [comment]
@sigu To be clear, my example names the gemsets, both, after the project AND the Rails version: `visualizer-rails5.0` 

And yes, it would require creating a new gemset when upgrading Rails version. That's kind of the point; a means to safely organize upgrades. Coupled with a new branch, say, `git checkout -b upgrade_to_Rails_5.1`, you can ensure a less painful upgrade that doesn't cause a chain of breaking dependencies. 
 
These are just additional organizational steps. With good test coverage, and spare time in case dependency update management is necessary, it's not really an issue. People have different workflow preferences.
 
You got the name of the project, which is the most important part. 😄  Don't let me stop you from merging the PR.

**Comment by sigu** [comment]
@FedericoEsparza it wont hurt to go with your workflow. From the gem conflict issues I have faced earlier in other projects (remember the `pg` gem issue 😃 ) your method would be way better 👍

**Pull request merged**
